apiVersion: v1
kind: Service
metadata:
  name: {{ include "flume.fullname" . }}-aggregator
  labels:
    {{- include "flume.labels" . | nindent 4 }}
    app.kubernetes.io/component: aggregator
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
    - name: grpc
      port: {{ .Values.aggregator.grpcPort }}
      targetPort: grpc
      protocol: TCP
  selector:
    {{- include "flume.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: aggregator
