apiVersion: v1
kind: Service
metadata:
  name: {{ include "flume.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "flume.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "flume.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.httpPort }}
      targetPort: http
      protocol: TCP
    - name: forward
      port: {{ .Values.service.forwardPort }}
      targetPort: forward
      protocol: TCP
